# =============================================================================
# Main Infrastructure: S3 + CloudFront + ACM + Route 53
# =============================================================================

locals {
  bucket_name = "${var.project_name}-${var.environment}"
  domain_name = var.domain_name
  aliases     = var.environment == "prod" ? [local.domain_name, "www.${local.domain_name}"] : ["${var.environment}.${local.domain_name}"]
}

# =============================================================================
# Route 53 Hosted Zone
# =============================================================================

data "aws_route53_zone" "main" {
  name         = local.domain_name
  private_zone = false
}

# =============================================================================
# Shared ACM Certificate (Generated by Bootstrap in us-east-1)
# =============================================================================

data "aws_acm_certificate" "shared" {
  provider = aws.us_east_1

  domain   = local.domain_name
  statuses = ["ISSUED"]
}

# =============================================================================
# S3 Bucket (Private — accessed only via CloudFront OAC)
# =============================================================================

resource "aws_s3_bucket" "website" {
  bucket = local.bucket_name

  tags = {
    Name = "${var.project_name} Website - ${var.environment}"
  }
}

resource "aws_s3_bucket_public_access_block" "website" {
  bucket = aws_s3_bucket.website.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_versioning" "website" {
  bucket = aws_s3_bucket.website.id

  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "website" {
  bucket = aws_s3_bucket.website.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

# =============================================================================
# CloudFront Origin Access Control
# =============================================================================

resource "aws_cloudfront_origin_access_control" "website" {
  name                              = "${var.project_name}-${var.environment}-oac"
  description                       = "OAC for ${var.project_name} ${var.environment} S3 bucket"
  origin_access_control_origin_type = "s3"
  signing_behavior                  = "always"
  signing_protocol                  = "sigv4"
}

# =============================================================================
# S3 Bucket Policy (allows CloudFront OAC to read objects)
# =============================================================================

data "aws_iam_policy_document" "website_bucket_policy" {
  statement {
    sid    = "AllowCloudFrontServicePrincipal"
    effect = "Allow"

    principals {
      type        = "Service"
      identifiers = ["cloudfront.amazonaws.com"]
    }

    actions   = ["s3:GetObject"]
    resources = ["${aws_s3_bucket.website.arn}/*"]

    condition {
      test     = "StringEquals"
      variable = "AWS:SourceArn"
      values   = [aws_cloudfront_distribution.website.arn]
    }
  }
}

resource "aws_s3_bucket_policy" "website" {
  bucket = aws_s3_bucket.website.id
  policy = data.aws_iam_policy_document.website_bucket_policy.json
}

# =============================================================================
# CloudFront Distribution
# =============================================================================

resource "aws_cloudfront_distribution" "website" {
  enabled             = true
  is_ipv6_enabled     = true
  default_root_object = "index.html"
  aliases             = local.aliases
  price_class         = "PriceClass_200"
  comment             = "${var.project_name} (${var.environment})"
  wait_for_deployment = true

  origin {
    domain_name              = aws_s3_bucket.website.bucket_regional_domain_name
    origin_id                = "S3-${local.bucket_name}"
    origin_access_control_id = aws_cloudfront_origin_access_control.website.id
  }

  default_cache_behavior {
    allowed_methods  = ["GET", "HEAD", "OPTIONS"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "S3-${local.bucket_name}"

    # Use AWS managed CachingOptimized policy
    cache_policy_id = "658327ea-f89d-4fab-a63d-7e88639e58f6"

    viewer_protocol_policy = "redirect-to-https"
    compress               = true
  }

  # SPA routing — serve index.html for 403 (S3 returns 403 for missing keys with OAC)
  custom_error_response {
    error_code            = 403
    response_code         = 200
    response_page_path    = "/index.html"
    error_caching_min_ttl = 10
  }

  # SPA routing — serve index.html for 404
  custom_error_response {
    error_code            = 404
    response_code         = 200
    response_page_path    = "/index.html"
    error_caching_min_ttl = 10
  }

  viewer_certificate {
    acm_certificate_arn      = data.aws_acm_certificate.shared.arn
    ssl_support_method       = "sni-only"
    minimum_protocol_version = "TLSv1.2_2021"
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  tags = {
    Name = "${var.project_name}-${var.environment}"
  }
}

# =============================================================================
# Route 53 DNS Records → CloudFront
# =============================================================================

# Apex domain (lakshawcfhospitals.in)
resource "aws_route53_record" "apex" {
  count   = var.environment == "prod" ? 1 : 0

  zone_id         = data.aws_route53_zone.main.zone_id
  name            = local.domain_name
  type            = "A"
  allow_overwrite = true

  alias {
    name                   = aws_cloudfront_distribution.website.domain_name
    zone_id                = aws_cloudfront_distribution.website.hosted_zone_id
    evaluate_target_health = false
  }
}

resource "aws_route53_record" "apex_ipv6" {
  count   = var.environment == "prod" ? 1 : 0

  zone_id         = data.aws_route53_zone.main.zone_id
  name            = local.domain_name
  type            = "AAAA"
  allow_overwrite = true

  alias {
    name                   = aws_cloudfront_distribution.website.domain_name
    zone_id                = aws_cloudfront_distribution.website.hosted_zone_id
    evaluate_target_health = false
  }
}

# www subdomain (www.lakshawcfhospitals.in) — only for prod
resource "aws_route53_record" "www" {
  count = var.environment == "prod" ? 1 : 0

  zone_id         = data.aws_route53_zone.main.zone_id
  name            = "www.${local.domain_name}"
  type            = "A"
  allow_overwrite = true

  alias {
    name                   = aws_cloudfront_distribution.website.domain_name
    zone_id                = aws_cloudfront_distribution.website.hosted_zone_id
    evaluate_target_health = false
  }
}

resource "aws_route53_record" "www_ipv6" {
  count = var.environment == "prod" ? 1 : 0

  zone_id         = data.aws_route53_zone.main.zone_id
  name            = "www.${local.domain_name}"
  type            = "AAAA"
  allow_overwrite = true

  alias {
    name                   = aws_cloudfront_distribution.website.domain_name
    zone_id                = aws_cloudfront_distribution.website.hosted_zone_id
    evaluate_target_health = false
  }
}

# dev/staging subdomain records
resource "aws_route53_record" "subdomain" {
  count = var.environment != "prod" ? 1 : 0

  zone_id         = data.aws_route53_zone.main.zone_id
  name            = "${var.environment}.${local.domain_name}"
  type            = "A"
  allow_overwrite = true

  alias {
    name                   = aws_cloudfront_distribution.website.domain_name
    zone_id                = aws_cloudfront_distribution.website.hosted_zone_id
    evaluate_target_health = false
  }
}

resource "aws_route53_record" "subdomain_ipv6" {
  count = var.environment != "prod" ? 1 : 0

  zone_id         = data.aws_route53_zone.main.zone_id
  name            = "${var.environment}.${local.domain_name}"
  type            = "AAAA"
  allow_overwrite = true

  alias {
    name                   = aws_cloudfront_distribution.website.domain_name
    zone_id                = aws_cloudfront_distribution.website.hosted_zone_id
    evaluate_target_health = false
  }
}
